(define (lookup name assoc_list)
  (if (null? assoc_list) '()
    (if (eq? name (caar assoc_list)) (car assoc_list)
	   (lookup name (cdr assoc_list)))
  )
)

(define (lookup-env name environment)
  (if (null? environment) '() 
	 (if (null? (lookup name (car environment)))
      (lookup-env name (cdr environment))
		(lookup name (car environment))
    )
  )
)	
